name: Ejecución Automática de Pruebas de API

# El framework se ejecutará automáticamente ante cada Push o Pull Request en la rama main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest # Levanta una máquina virtual con Linux en GitHub

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Versión estable de Python para testing

    - name: Instalar dependencias necesarias
      run: |
        python -m pip install --upgrade pip
        pip install requests pytest pytest-html pytest-check

    - name: Ejecutar las pruebas de Pytest de la API
      run: |
        pytest api_testing/ --ini=api_testing/pytest.ini
      # Nota: Ajusta "api_testing/test/" si tu carpeta interna de pruebas se llama "tests" en plural

    - name: Guardar el Reporte HTML como artefacto del servidor
      if: always() # Hace que se guarde el reporte incluso si los tests fallaron
      uses: actions/upload-artifact@v4
      with:
        name: reporte-pytest-html
        path: api_testing/reports/